[package]
name = "constraints"
version = "0.1.0"
authors = ["gareth <gareth.charnock@zerolight.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lpsolve = "0.1.0"
